## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

def build(bld):
    # only build if in parallel
    if bld.env.MPI_FOUND:
        bld.shlib(
            source = 'GkMpiFuncs.cpp',
            target = 'gkcomm',
            includes = '.',
            use = 'MPI'
        )    
