## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bldFunc = bld.shlib
    
    # only build if in parallel
    if bld.env.MPI_FOUND:
        bldFunc(
            source = 'GkMpiFuncs.cpp',
            target = 'gkcomm',
            vnum="1.0",
            includes = '.',
            use = 'MPI'
        )    
