load("/Users/mana/Documents/Research/Gkeyll/Code/RecoveryModal/ConstDiffusion-surf")$
load(stringproc)$

/* Maximum polynomial order to generate kernels for */
inMaxPolyOrder : 4$

for c : 1 thru 3 do (
  fname : sconcat("~/max-out/ConstDiffusionSurfSer", c, "x", ".cpp"),
  fh : openw(fname),
  funcName : sconcat("ConstDiffusionSurf", c, "x", "Ser"),
  calcConstDiffusionSurfUpdater(fh, funcName, c, "Ser", inMaxPolyOrder),
  close(fh)
);
