load("constDiffusion-calc/ConstDiffusion-surf")$
load(stringproc)$

/* Maximum polynomial order to generate kernels for */
inMaxPolyOrder : 4$

for c : 1 thru 3 do (
  fname : sconcat("~/max-out/ConstDiffusionSurfMax", c, "x", ".cpp"),
  fh : openw(fname),
  funcName : sconcat("ConstDiffusionSurf", c, "x", "Max"),
  calcConstDiffusionSurfUpdater(fh, funcName, c, "Max", inMaxPolyOrder),
  close(fh)
);
