## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.shlib(
        source = 'CartFieldImpl.cpp',
        target = 'datastruct', name = 'datastruct', vnum = '1.0',
        includes = '.'
    )
