#ifndef MG_POISSON_MOD_DECL_H 
#define MG_POISSON_MOD_DECL_H 
 
#include <cmath>
 
extern "C" { 
 
void MGpoissonDGProlong1xSer_P1(const double *fldC, double **fldF);
void MGpoissonDGRestrict1xSer_P1(double **fldF, double *fldC);

void MGpoissonDGDampedGaussSeidel1xSer_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi1xSer_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel1xSer_LxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel1xSer_UxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi1xSer_LxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi1xSer_UxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);

void MGpoissonDGResidue1xSer_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue1xSer_LxRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue1xSer_UxRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);

void MGpoissonFEM_DGtoFEM_1xSer_P1(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_1xSer_Lx_P1(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_1xSer_Ux_P1(const double *dgFld, double **femOut);

void MGpoissonFEMDampedJacobi1xSer_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_LxDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_LxNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_LxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_UxDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_UxNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_UxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_LxDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_LxNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_LxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_UxDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_UxNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_UxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);

void MGpoissonFEMProlong1xSer_P1(const double *fldC, double **fldF);
void MGpoissonFEMProlong1xSer_LxNonPeriodic_P1(const double *fldC, double **fldF);
void MGpoissonFEMProlong1xSer_UxNonPeriodic_P1(const double *fldC, double **fldF);
void MGpoissonFEMRestrict1xSer_P1(double **fldF, double *fldC);
void MGpoissonFEMRestrict1xSer_LxNonPeriodic_P1(double **fldF, double *fldC);
void MGpoissonFEMRestrict1xSer_UxNonPeriodic_P1(double **fldF, double *fldC);

void MGpoissonFEMResidue1xSer_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_LxDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_LxNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_LxRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_UxDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_UxNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_UxRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);

void MGpoissonFEML2norm1xSer_P1(double **femFld, double *normOut);
void MGpoissonFEML2norm1xSer_LxNonPeriodic_P1(double **femFld, double *normOut);
void MGpoissonFEML2norm1xSer_UxNonPeriodic_P1(double **femFld, double *normOut);

void MGpoissonDGProlong2xSer_P1(const double *fldC, double **fldF);
void MGpoissonDGRestrict2xSer_P1(double **fldF, double *fldC);

void MGpoissonDGDampedGaussSeidel2xSer_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_LxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_UxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_LyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_UyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_LxRobinLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_LxRobinUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_UxRobinLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_UxRobinUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_LxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_UxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_LyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_UyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_LxRobinLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_LxRobinUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_UxRobinLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_UxRobinUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);

void MGpoissonDGResidue2xSer_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_LxRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_UxRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_LyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_UyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_LxRobinLyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_LxRobinUyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_UxRobinLyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_UxRobinUyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);

void MGpoissonFEM_DGtoFEM_2xSer_P1(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_Lx_P1(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_Ux_P1(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_Ly_P1(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_Uy_P1(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_LxLy_P1(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_LxUy_P1(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_UxLy_P1(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_UxUy_P1(const double *dgFld, double **femOut);

void MGpoissonFEMDampedJacobi2xSer_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinLyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinLyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinLyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinUyDirichlet_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinUyNeumann_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinUyRobin_P1(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);

void MGpoissonFEMProlong2xSer_P1(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_LxNonPeriodic_P1(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_UxNonPeriodic_P1(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_LyNonPeriodic_P1(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_UyNonPeriodic_P1(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_LxNonPeriodicLyNonPeriodic_P1(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_LxNonPeriodicUyNonPeriodic_P1(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_UxNonPeriodicLyNonPeriodic_P1(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_UxNonPeriodicUyNonPeriodic_P1(const double *fldC, double **fldF);
void MGpoissonFEMRestrict2xSer_P1(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_LxNonPeriodic_P1(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_UxNonPeriodic_P1(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_LyNonPeriodic_P1(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_UyNonPeriodic_P1(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_LxNonPeriodicLyNonPeriodic_P1(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_LxNonPeriodicUyNonPeriodic_P1(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_UxNonPeriodicLyNonPeriodic_P1(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_UxNonPeriodicUyNonPeriodic_P1(double **fldF, double *fldC);

void MGpoissonFEMResidue2xSer_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletLyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletLyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletLyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannLyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannLyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannLyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinLyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinLyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinLyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletUyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletUyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletUyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannUyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannUyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannUyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinUyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinUyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinUyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletLyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletLyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletLyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannLyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannLyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannLyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinLyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinLyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinLyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletUyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletUyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletUyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannUyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannUyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannUyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinUyDirichlet_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinUyNeumann_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinUyRobin_P1(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);

void MGpoissonFEML2norm2xSer_P1(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_LxNonPeriodic_P1(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_UxNonPeriodic_P1(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_LyNonPeriodic_P1(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_UyNonPeriodic_P1(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_LxNonPeriodicLyNonPeriodic_P1(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_LxNonPeriodicUyNonPeriodic_P1(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_UxNonPeriodicLyNonPeriodic_P1(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_UxNonPeriodicUyNonPeriodic_P1(double **femFld, double *normOut);


void MGpoissonDGProlong1xSer_P2(const double *fldC, double **fldF);
void MGpoissonDGRestrict1xSer_P2(double **fldF, double *fldC);

void MGpoissonDGDampedGaussSeidel1xSer_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi1xSer_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel1xSer_LxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel1xSer_UxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi1xSer_LxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi1xSer_UxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);

void MGpoissonDGResidue1xSer_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue1xSer_LxRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue1xSer_UxRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);

void MGpoissonFEM_DGtoFEM_1xSer_P2(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_1xSer_Lx_P2(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_1xSer_Ux_P2(const double *dgFld, double **femOut);

void MGpoissonFEMDampedJacobi1xSer_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_LxDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_LxNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_LxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_UxDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_UxNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi1xSer_UxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_LxDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_LxNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_LxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_UxDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_UxNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel1xSer_UxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);

void MGpoissonFEMProlong1xSer_P2(const double *fldC, double **fldF);
void MGpoissonFEMProlong1xSer_LxNonPeriodic_P2(const double *fldC, double **fldF);
void MGpoissonFEMProlong1xSer_UxNonPeriodic_P2(const double *fldC, double **fldF);
void MGpoissonFEMRestrict1xSer_P2(double **fldF, double *fldC);
void MGpoissonFEMRestrict1xSer_LxNonPeriodic_P2(double **fldF, double *fldC);
void MGpoissonFEMRestrict1xSer_UxNonPeriodic_P2(double **fldF, double *fldC);

void MGpoissonFEMResidue1xSer_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_LxDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_LxNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_LxRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_UxDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_UxNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue1xSer_UxRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);

void MGpoissonFEML2norm1xSer_P2(double **femFld, double *normOut);
void MGpoissonFEML2norm1xSer_LxNonPeriodic_P2(double **femFld, double *normOut);
void MGpoissonFEML2norm1xSer_UxNonPeriodic_P2(double **femFld, double *normOut);

void MGpoissonDGProlong2xSer_P2(const double *fldC, double **fldF);
void MGpoissonDGRestrict2xSer_P2(double **fldF, double *fldC);

void MGpoissonDGDampedGaussSeidel2xSer_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_LxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_UxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_LyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_UyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_LxRobinLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_LxRobinUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_UxRobinLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedGaussSeidel2xSer_UxRobinUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_LxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_UxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_LyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_UyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_LxRobinLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_LxRobinUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_UxRobinLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonDGDampedJacobi2xSer_UxRobinUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);

void MGpoissonDGResidue2xSer_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_LxRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_UxRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_LyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_UyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_LxRobinLyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_LxRobinUyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_UxRobinLyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonDGResidue2xSer_UxRobinUyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);

void MGpoissonFEM_DGtoFEM_2xSer_P2(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_Lx_P2(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_Ux_P2(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_Ly_P2(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_Uy_P2(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_LxLy_P2(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_LxUy_P2(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_UxLy_P2(const double *dgFld, double **femOut);
void MGpoissonFEM_DGtoFEM_2xSer_UxUy_P2(const double *dgFld, double **femOut);

void MGpoissonFEMDampedJacobi2xSer_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxDirichletUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxNeumannUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_LxRobinUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxDirichletUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxNeumannUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedJacobi2xSer_UxRobinUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxDirichletUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxNeumannUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_LxRobinUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinLyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinLyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinLyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxDirichletUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxNeumannUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinUyDirichlet_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinUyNeumann_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);
void MGpoissonFEMDampedGaussSeidel2xSer_UxRobinUyRobin_P2(const double omega, double **dx, const double *bcVals, double **rho, double **phiPrev, double **phi);

void MGpoissonFEMProlong2xSer_P2(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_LxNonPeriodic_P2(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_UxNonPeriodic_P2(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_LyNonPeriodic_P2(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_UyNonPeriodic_P2(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_LxNonPeriodicLyNonPeriodic_P2(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_LxNonPeriodicUyNonPeriodic_P2(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_UxNonPeriodicLyNonPeriodic_P2(const double *fldC, double **fldF);
void MGpoissonFEMProlong2xSer_UxNonPeriodicUyNonPeriodic_P2(const double *fldC, double **fldF);
void MGpoissonFEMRestrict2xSer_P2(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_LxNonPeriodic_P2(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_UxNonPeriodic_P2(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_LyNonPeriodic_P2(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_UyNonPeriodic_P2(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_LxNonPeriodicLyNonPeriodic_P2(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_LxNonPeriodicUyNonPeriodic_P2(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_UxNonPeriodicLyNonPeriodic_P2(double **fldF, double *fldC);
void MGpoissonFEMRestrict2xSer_UxNonPeriodicUyNonPeriodic_P2(double **fldF, double *fldC);

void MGpoissonFEMResidue2xSer_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletLyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletLyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletLyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannLyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannLyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannLyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinLyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinLyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinLyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletUyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletUyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxDirichletUyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannUyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannUyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxNeumannUyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinUyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinUyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_LxRobinUyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletLyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletLyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletLyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannLyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannLyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannLyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinLyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinLyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinLyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletUyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletUyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxDirichletUyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannUyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannUyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxNeumannUyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinUyDirichlet_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinUyNeumann_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);
void MGpoissonFEMResidue2xSer_UxRobinUyRobin_P2(double **dx, const double *bcVals, double **rho, double **phi, double *resOut);

void MGpoissonFEML2norm2xSer_P2(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_LxNonPeriodic_P2(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_UxNonPeriodic_P2(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_LyNonPeriodic_P2(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_UyNonPeriodic_P2(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_LxNonPeriodicLyNonPeriodic_P2(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_LxNonPeriodicUyNonPeriodic_P2(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_UxNonPeriodicLyNonPeriodic_P2(double **femFld, double *normOut);
void MGpoissonFEML2norm2xSer_UxNonPeriodicUyNonPeriodic_P2(double **femFld, double *normOut);


} 
#endif 
