load("modal-basis");
load("out-scripts");
fpprec : 24$

var : [z1, z2, z3, z4, z5]$

fh : openw("~/max-out/ModalMaxOrderBasis5d.lua");
printf(fh, "local _M = {} ~%");

for i : 1 thru 4 do (
  printf(fh, "_M[~a] = function (z, b) ~%", i),
  printf(fh, "   local z1, z2, z3, z4, z5 = z[1], z[2], z[3], z[4], z[5] ~%", i),
  basis : gsOrthoNorm(var, makeMaxOrderBasis(var, i)),
  writeBasis(fh, float(basis)),
  printf(fh, "end ~%")
);

printf(fh, "return _M ~%");
close(fh);
