load("modal-basis");
load("out-scripts");
fpprec : 24$

var : [z1]$

fh : openw("~/max-out/ModalBasis1d.lua");
printf(fh, "local _M = {} ~%");

for i : 1 thru 9 do (
  printf(fh, "_M[~a] = function (z, b) ~%", i),
  printf(fh, "   local z1 = z[1] ~%", i),
  basis : gsOrthoNorm(var, makeSerendipBasis(var, i)),
  writeBasis(fh, float(basis)),
  printf(fh, "end ~%")
);

printf(fh, "return _M ~%");
close(fh);
