## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.objects(source = r"""
    TenMomentImpl.cpp

    maxwellData/MaxwellVolSer1x.cpp
    maxwellData/MaxwellVolSer2x.cpp
    maxwellData/MaxwellVolSer3x.cpp

    maxwellData/MaxwellSurfSer1x.cpp
    maxwellData/MaxwellSurfSer2x.cpp
    maxwellData/MaxwellSurfSer3x.cpp

    maxwellData/MaxwellVolMax1x.cpp
    maxwellData/MaxwellVolMax2x.cpp
    maxwellData/MaxwellVolMax3x.cpp

    maxwellData/MaxwellSurfMax1x.cpp
    maxwellData/MaxwellSurfMax2x.cpp
    maxwellData/MaxwellSurfMax3x.cpp

    """,
    target = 'eq', includes = '. maxwellData'
    )
