## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.objects(source = r"""
    TenMomentImpl.cpp

    lboData/VmLBOconstNuSer1x1v.cpp
    lboData/VmLBOconstNuSurfSer1x1v.cpp
    lboData/VmLBOconstNuSer1x2v.cpp
    lboData/VmLBOconstNuSurfSer1x2v.cpp
    lboData/VmLBOconstNuSer2x2v.cpp
    lboData/VmLBOconstNuSurfSer2x2v.cpp

    constDiffusionData/ConstDiffusionSer1x.cpp
    constDiffusionData/ConstDiffusionSer2x.cpp
    constDiffusionData/ConstDiffusionSer3x.cpp

    constDiffusionData/ConstDiffusionSurfSer1x.cpp
    constDiffusionData/ConstDiffusionSurfSer2x.cpp
    constDiffusionData/ConstDiffusionSurfSer3x.cpp

    maxwellData/MaxwellVolSer1x.cpp
    maxwellData/MaxwellVolSer2x.cpp
    maxwellData/MaxwellVolSer3x.cpp

    maxwellData/MaxwellSurfSer1x.cpp
    maxwellData/MaxwellSurfSer2x.cpp
    maxwellData/MaxwellSurfSer3x.cpp

    maxwellData/MaxwellVolMax1x.cpp
    maxwellData/MaxwellVolMax2x.cpp
    maxwellData/MaxwellVolMax3x.cpp

    maxwellData/MaxwellSurfMax1x.cpp
    maxwellData/MaxwellSurfMax2x.cpp
    maxwellData/MaxwellSurfMax3x.cpp

    vlasovData/VlasovStreamMax1x1v.cpp
    vlasovData/VlasovStreamMax1x2v.cpp
    vlasovData/VlasovStreamMax1x3v.cpp
    vlasovData/VlasovStreamMax2x2v.cpp
    vlasovData/VlasovStreamMax2x3v.cpp
    vlasovData/VlasovStreamMax3x3v.cpp

    vlasovData/VlasovStreamSer1x1v.cpp
    vlasovData/VlasovStreamSer1x2v.cpp
    vlasovData/VlasovStreamSer1x3v.cpp
    vlasovData/VlasovStreamSer2x2v.cpp
    vlasovData/VlasovStreamSer2x3v.cpp
    vlasovData/VlasovStreamSer3x3v.cpp

    vlasovData/VlasovSurfStreamMax1x1v.cpp
    vlasovData/VlasovSurfStreamMax1x2v.cpp
    vlasovData/VlasovSurfStreamMax1x3v.cpp
    vlasovData/VlasovSurfStreamMax2x2v.cpp
    vlasovData/VlasovSurfStreamMax2x3v.cpp
    vlasovData/VlasovSurfStreamMax3x3v.cpp

    vlasovData/VlasovSurfStreamSer1x1v.cpp
    vlasovData/VlasovSurfStreamSer1x2v.cpp
    vlasovData/VlasovSurfStreamSer1x3v.cpp
    vlasovData/VlasovSurfStreamSer2x2v.cpp
    vlasovData/VlasovSurfStreamSer2x3v.cpp
    vlasovData/VlasovSurfStreamSer3x3v.cpp

    vlasovData/VlasovElcMagMax1x1v.cpp
    vlasovData/VlasovElcMagMax1x2v.cpp
    vlasovData/VlasovElcMagMax1x3v.cpp
    vlasovData/VlasovElcMagMax2x2v.cpp
    vlasovData/VlasovElcMagMax2x3v.cpp
    vlasovData/VlasovElcMagMax3x3v.cpp

    vlasovData/VlasovElcMagSer1x1v.cpp
    vlasovData/VlasovElcMagSer1x2v.cpp
    vlasovData/VlasovElcMagSer1x3v.cpp
    vlasovData/VlasovElcMagSer2x2v.cpp
    vlasovData/VlasovElcMagSer2x3v.cpp
    vlasovData/VlasovElcMagSer3x3v.cpp

    vlasovData/VlasovSurfElcMagMax1x1v.cpp
    vlasovData/VlasovSurfElcMagMax1x2v.cpp
    vlasovData/VlasovSurfElcMagMax1x3v.cpp
    vlasovData/VlasovSurfElcMagMax2x2v.cpp
    vlasovData/VlasovSurfElcMagMax2x3v.cpp
    vlasovData/VlasovSurfElcMagMax3x3v.cpp

    vlasovData/VlasovSurfElcMagSer1x1v.cpp
    vlasovData/VlasovSurfElcMagSer1x2v.cpp
    vlasovData/VlasovSurfElcMagSer1x3v.cpp
    vlasovData/VlasovSurfElcMagSer2x2v.cpp
    vlasovData/VlasovSurfElcMagSer2x3v.cpp
    vlasovData/VlasovSurfElcMagSer3x3v.cpp

    vlasovData/VlasovIncr.cpp

    pbData/CanonicalMax1x1v.cpp
    pbData/CanonicalMax2x2v.cpp
    pbData/CanonicalSer1x1v.cpp
    pbData/CanonicalSer2x2v.cpp
    pbData/CanonicalSurfMax1x1v.cpp
    pbData/CanonicalSurfMax2x2v.cpp
    pbData/CanonicalSurfSer1x1v.cpp
    pbData/CanonicalSurfSer2x2v.cpp
    pbData/CanonicalDisContSurfSer1x1v.cpp

    gkData/GyrokineticSer1x1v.cpp
    gkData/GyrokineticSer2x2v.cpp
    gkData/GyrokineticSer3x2v.cpp
    gkData/GyrokineticSurfSer1x1v.cpp
    gkData/GyrokineticSurfSer2x2v.cpp
    gkData/GyrokineticSurfSer3x2v.cpp
    gkData/GkSheathFuncsSer.cpp

    """,
    target = 'eq', use='EIGEN', includes = '. lboData constDiffusionData maxwellData vlasovData pbData gkData ../Updater/binOpCalcData'
    )

