## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os
from waflib import Utils

def build(bld):
    sources = r"""
    """

    ## HyperDisContDeviceShared.cu
    # CUDA specific code
    if bld.env['CUTOOLS_FOUND']:
        cusources = r"""
        DummyStructDevice.cu
        """

        bld(source = cusources,
            name = 'updater_cu', target='updater_cu',
            includes = '. ../Cuda ../Grid ../Lib ../Basis ../Eq ../DataStruct momentCalcData ../Eq/vlasovData', features = 'cxx nvcc '
        )


    bld.shlib(source = sources,

              includes = '. ../Cuda',
              use='lib MPI CUTOOLS gkylzero', target = 'updater', name = 'updater', vum = '1.0', features = 'cxx')
    
## Removed the following files from the build for now
#    interpolateCalcData/CartFieldInterpSer1x.cpp
#    interpolateCalcData/CartFieldInterpSer2x.cpp
#
#    projectFluxOnGhostsData/ProjectFluxOnGhostsSer.cpp
#
#    EvaluateBronoldFehskeBCImpl.cpp

#    MomentSrcCommon.cpp
#    FiveMomentSrcImpl.cpp
#    TenMomentSrcImpl.cpp
#    TenMomentRelaxImpl.cpp
#    AxisymmetricFiveMomentSrcImpl.cpp
#    AxisymmetricPhMaxwellSrcImpl.cpp
#    FiveMomentFrictionSrcImpl.cpp
#
#    FemMatrices.cpp
#    FemPerpPoissonImpl.cpp
#    FemParPoissonImpl.cpp
#
#    DiscontPoissonImpl.cpp  
#    FemGyroaverageImpl.cpp
#    MappedPoissonImpl.cpp
#    EvalOnNodesImpl.cpp
#
#     binOpCalcData/CartFieldBinOpSer3x3vP2.cpp
#    lagrangeFixData/lagrangeFix_gk_1x2v_ser_p2.cpp
#    lagrangeFixData/lagrangeFix_gk_1x2v_tensor_p2.cpp
#    lagrangeFixData/lagrangeFix_gk_2x2v_max_p1.cpp
#    lagrangeFixData/lagrangeFix_gk_2x2v_ser_p1.cpp
#    lagrangeFixData/lagrangeFix_gk_2x2v_tensor_p1.cpp
