## -*- python -*-
import os

# extra flags to pass to linker
EXTRA_LINK_FLAGS = []

def build(bld):
    r"""Build top-level executable"""
    uname = os.uname()
    if uname[0] == 'Darwin' and uname[4] == 'x86_64':
        # we need to append special flags to get stuff to work on a Mac
        EXTRA_LINK_FLAGS.append('-pagezero_size 10000 -image_base 100000000')

    # build idjit executable
    bld.program(
        source='xgkyl.cxx', target='xgkyl',
        use='LUAJIT M DL',
        linkflags = EXTRA_LINK_FLAGS
    )
    # install shell-script
    bld.install_files("${PREFIX}/bin", ["gkyl"])
