load("modal-basis");
load("out-scripts");

PB(f,g) := diff(f,z1)*diff(g,z2) - diff(g,z1)*diff(f,z2)$
doExpand(f,basis) := sum(f[i]*basis[i], i, 1, length(basis))$

vars : [z1, z2]$
basis : gsOrthoNorm(vars, makeSerendipBasis(vars, 1))$

He : doExpand1(H,basis)$
fe : doExpand1(f,basis)$

volTerm(i) := innerProd(vars, 1, PB(basis[i],He)*fe, 1)$
volTerms : makelist(fullratsimp(volTerm(i)), i, 1, length(basis))$