package:
  name: adiospy
  version: "1.12.0"

source:
  path: ./

requirements:
  build:
    - python
    - numpy
    - adios
  run:
    - python
    - numpy
    - adios

test:
  imports:
    - adios

about:
  home: https://www.olcf.ornl.gov/center-projects/adios/