## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.objects(source = 'test_cfuncs.cpp', includes = '.', target = 'unit')
