## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.objects(
        source = 'RectCartImpl.cpp',
        target = 'grid',
        includes = '.'
    )
