## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.shlib(
        source = 'RectCartImpl.cpp',
        target = 'grid', name = 'grid', vnum = '1.0',
        includes = '.'
    )
