load("basis-precalc/basis-pre-calc");

/*
for c : 1 thru 2 do (
  for v : c thru 3 do (
   fname : sconcat("~/max-out/basisSer", c, "x", v, "v", ".lisp"),
   writeBasisToFile(c, v, 4, makeSerendipBasis, fname)
  )
)$

writeBasisToFile(3, 3, 4, makeSerendipBasis, "~/max-out/basisSer3x3v.lisp")$
writeBasisToFile(3, 2, 4, makeSerendipBasis, "~/max-out/basisSer3x2v.lisp")$*/
writeBasisToFile(3, 1, 4, makeSerendipBasis, "~/max-out/basisSer3x1v.lisp")$
