## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bldFunc = bld.shlib
    bldFunc(source = r"""
    """,
    includes = '. ./_data', target = 'basis', name = 'basis', vnum="1.0")
