## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    uname = os.uname()
    if uname[0] == 'Darwin':
        bldFunc = bld.shlib
    else:
        bldFunc = bld.stlib
    
    bldFunc(source = r"""
    """,
    includes = '. ./_data', target = 'gkbasis', vnum="1.0")
