## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.shlib(source = "gkyl_ipow.cpp whereami.c base64.cpp lfs.c",
              use = "LUAJIT", includes = '.', target = 'lib', name = 'lib', vnum = '1.0')
