## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bldFunc = bld.shlib

    bld.objects(source = 'lfs.c', use = "LUAJIT", includes = '.', target = 'lfs')
    #bldFunc(source = 'lfsobjs', target = 'lfs', vnum="1.0")
