## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.shlib(source = 'ExactEulerRpImpl.cpp', includes = '.',
              name = 'tool',
              vnum = '1.0',
              target = 'tool', features='cxx')
