## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.shlib(source = r"""
    proto_kernel.cpp
    """,
    includes = '.', use='Eigen MPI lib', target = 'proto', name='proto', vnum = '1.0')
