## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.objects(source = r"""
    Fpo/fpoMomsKernelP1.cpp

    Fpo/fpoDiagKernelP1.cpp

    Fpo/fpoDragKernelP1.cpp

    Fpo/fpoDiffKernelP1.cpp
    """,
    includes = '. Fpo', use='Eigen MPI', target = 'proto')

# def build(bld):
#     bld.objects(source = r"""
#     Fpo/fpoMomsKernelP1.cpp
#     Fpo/fpoMomsKernelP2.cpp

#     Fpo/fpoDiagKernelP1.cpp
#     Fpo/fpoDiagKernelP2.cpp

#     Fpo/fpoDragKernelP1.cpp
#     Fpo/fpoDragKernelP2.cpp

#     Fpo/fpoDiffKernelP1.cpp
#     Fpo/fpoDiffKernelP2.cpp
#     """,
#     includes = '. Fpo', use='Eigen MPI', target = 'proto')
