## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    pass
    # bld.objects(
    #     use = "LUAJIT", includes = '.', target = 'lib'
    # )
