load("/Users/ahakim/research/gkyl-project/gkyl/cas-scripts/vlasov-calc/vlasov-stream-vol.mac")$
load(stringproc)$

for c : 1 thru 2 do (
  for v : c thru 3 do (
   fname : sconcat("~/max-out/VlasovStreamMax", c, "x", v, "v", ".cpp"),
   fh : openw(fname),
   funcName : sconcat("VlasovVolStream", c, "x", v, "v", "Max"),
   calcVlasovVolUpdater(fh, funcName, c, v, makevarsP(c,v), makeMaxOrderBasis),
   close(fh)
  )
);
