package:
  name: adios
  version: "1.11.0"

source:
  path: ./

build:
  number: 0

requirements:
  build:
    - openmpi
  run:
    - openmpi

about:
  home: https://www.olcf.ornl.gov/center-projects/adios/