package:
  name: adios
  version: "1.11.0"

source:
  path: ./

build:
  number: 0

requirements:
  build:
    - openmpi 2.0.2
  run:
    - openmpi 2.0.2

about:
  home: https://bitbucket.org/ammarhakim/gkylcd 