## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.objects(source = r"""
    sqlite3.c""",
    use = "LUAJIT", includes = '.', target = 'sqlite3')
