## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.shlib(source = r"""
    sqlite3.c""",
    use = "LUAJIT", includes = '.', target = 'gksqlite3', name = 'sqlite3', vnum = '1.0')
