package:
  name: gkyl
  version: "0.9.0"

source:
  path: ../../

build:
  number: 1

requirements:
  build:
    - luajit
    - adios >=1.13.0
    - openmpi >=3.0.0
    - eigen3
  run:
    - luajit
    - adios >=1.13.0
    - openmpi >=3.0.0
    - eigen3

about:
  home: https://bitbucket.org/ammarhakim/gkyl
  license: 'Gkyl can be used freely for research at universities, national laboratories and other non-profit institutions'
  summary: 'Efficient and robust open-source framework for laboratory, geophysical and astrophysical plasma physics'