package:
  name: gkyl
  version: "1.0.1"

source:
  path: ../../

build:
  number: 42

requirements:
  build:
    - luajit
    - adios
    - openmpi
  run:
    - luajit
    - adios
    - openmpi

about:
  home: https://bitbucket.org/ammarhakim/gkyl