package:
  name: gkeyll
  version: "2.0"

source:
  path: ../../

build:
  number: 20190303

requirements:
  build:
    - luajit
    - adios >=1.13.0
    - openmpi >=3.1.2
    - eigen3
  run:
    - luajit
    - adios >=1.13.0
    - openmpi >=3.1.2
    - eigen3
    - postgkyl

about:
  home: https://bitbucket.org/ammarhakim/gkeyll
  license: 'We follow a open-source but closed development model. Even though read access to the code is available to everyone, write access to the source-code repository is restricted to those who need to modify the code. In practice, this means researchers at PPPL and our partner institutions. In particular, this means that for write access you either need to have jointly funded projects or jointly supervised graduate students with Princeton University/PPPL.
Gkeyll, Postgkyl and this documentation is copyrighted 2016-2018 by Ammar Hakim.'
  summary: 'Efficient and robust open-source framework for laboratory, geophysical and astrophysical plasma physics'